Language and different supplier support based on list
helsingborg-stad/styleguide pull request #543
Opened 2022-09-22 10:23 UTC by NiclasNorin

2022-09-23 08:18 UTC, annalinneajohansson reviewed
Kvarglömda console.log på rad 50 och 53 :)

2022-09-23 14:15 UTC, helsingborgsstad commented
Task linked: [CU-3f2z3ph Hantera godkännande av iframe med javascript ](https://app.clickup.com/t/3f2z3ph)

2022-10-04 09:06 UTC, sebastianthulin requested changes

2022-10-07 06:52 UTC, NiclasNorin commented on source/js/iframeAcceptance.js
> +                if (iframe.getAttribute('data-supplier') && iframe.getAttribute('data-policy')) {
Func removed in latest commits

2022-10-07 06:53 UTC, NiclasNorin commented on source/js/iframeAcceptance.js
> +                    const supplier = options.infoText.replace('{SUPPLIER_WEBSITE}', iframe.getAttribute('data-supplier')).replace('{SUPPLIER_POLICY}', iframe.getAttribute('data-policy'));
Removed and uses backend instead

2022-10-07 06:54 UTC, NiclasNorin commented on source/js/iframeAcceptance.js
>              const div = document.createElement('div');
Moved to backend

2022-10-07 06:54 UTC, NiclasNorin commented on source/js/iframeAcceptance.js
>              div.insertAdjacentHTML('beforeend', template({ titleText, infoText, buttonText }));
Removed and moved to backend

2022-10-07 08:22 UTC, NiclasNorin commented on source/js/iframeAcceptance.js
> +const template = ({ title, info, button }) => (`
Gets rendered in PHP now

2022-10-11 07:53 UTC, merged