Center Acceptance play button
helsingborg-stad/styleguide pull request #644
Opened 2022-12-20 12:59 UTC by thorbrink

2022-12-20 13:00 UTC, helsingborgsstad commented
Task linked: [CU-3x18258 Snygga till play-knappen för video?](https://app.clickup.com/t/3x18258)

2022-12-21 07:50 UTC, sebastianthulin requested changes

2022-12-21 07:50 UTC, sebastianthulin commented on source/sass/component/_acceptance.scss
> +                text-shadow: 0 0 10px rgba(0,0,0,0.5);
This may be interfering with other design decisions (visually). Consider using one of the shadow level vars.

2022-12-21 07:50 UTC, sebastianthulin commented on source/sass/component/_acceptance.scss
> +                text-shadow: 0 0 10px rgba(0,0,0,0.5);
Also: Try using a calculation of $base for any sizes (8px).

2022-12-22 08:10 UTC, sebastianthulin approved these changes

2022-12-22 08:10 UTC, merged